version: 0.2
phases:
  install:
    commands:
      - npm ci
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - aws s3 sync build/ s3://$TARGET_BUCKET/ --delete --cache-control "public,max-age=31536000,immutable" --exclude "index.html"
      - aws s3 cp build/index.html s3://$TARGET_BUCKET/index.html --cache-control "no-cache"
artifacts:
  files:
    - '**/*'
  discard-paths: yes